### ISSUE TITLE
Reference jobs resources are missing flags

### ISSUE THREAD

**Issue by b0tting** [rundeck/terraform-provider-rundeck#127]
When creating a reference job in Rundeck you can pass 4 flags that allow you to modify the way the parent and child job interact. 

![afbeelding](https://github.com/rundeck/terraform-provider-rundeck/assets/10924289/2bc5b948-3a59-4aff-898a-9256a9912dce)

Especially the first flag is very useful to me. I can set up jobs with a lot of parameters, then reference that jobs and overwrite just a few parameters. At the moment of writing, I cannot find any reference to these four flags in the terraform-provider-rundeck code or the documentation, which feels like they are not implemented. 

They are in the job exports from Rundeck, for example, an export with the "Import options" and "Ignore notifications" set: 
```
    commands:
    - jobref:
        group: MyReferenceJobs
        ignoreNotifications: true    
        importOptions: true   
        name: MyChildJob
        useName: 'true'
    keepgoing: false
    strategy: node-first
```

### Terraform Version
```
Terraform v1.8.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/rundeck/rundeck v0.4.7

Your version of Terraform is out of date! The latest version
is 1.8.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- rundeck_job.command.job

### Terraform Configuration Files
```hcl
resource "rundeck_job" "child_job" {
  name                      = "my_child_job"
  project_name              = rundeck_project.project.name

  command {
    job {
      name       = rundeck_job.sync_1password_rundeck.name
      group_name = rundeck_job.sync_1password_rundeck.group_name
      import_options = true          # Errors as │ An argument named "import_options" is not expected here.

      }
    }
  }


```

### Expected Behavior
These flags to be accepted and passed into the import file created by the terraform provider
